config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }, presence: true
  validates :list_id, uniqueness: { scope: :movie_id }, presence: true
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks #, dependent: :destroy_async
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit destroy]
  before_action :set_list, only: %i[new create]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: "Bookmark was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    list_id = @bookmark.list.id
    @bookmark.destroy
    redirect_to list_path(list_id), status: :see_other
  end

private


  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to @list, notive: "List was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(rest_params)
      redirect_to @list, notice: "List was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

private

def set_list
  @list = List.find(params[:id])
end
end

def list_params
  params.require(:list).permit(:name, :photo)
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show]
  
  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

private

  def set_review
    @review = Review.find(params[:review_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/index.html.erb
<div class = 'container'>
<h1> <%= @list.name %> % </h1>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.name %></li>
  <% end %>
<button type="button" class="btn btn-tertiary"><%= link_to "Add a movie", new_bookmark_path %></button>
</ul>
</div>

app/views/bookmarks/new.html.erb
<div class ="container py-5">
  <div class= "row">
    <div class="col-12 col-md-6 offset-lg-3">
    <h2> Add a movie to:  </h2>
    <h3><i><%= @list.name %></i></h3>
    <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.association :movie %>
      <%= f.input :comment %>
    </div>

    <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-ghost" %>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">
      <i class="fa-solid fa-film"></i>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <li class="nav-item active">
      <a class="nav-link" <%= link_to "My lists",lists_path %>
      </a>
      </li>
      <li class="nav-item">
      <a class="nav-link" <%= link_to "New list", new_list_path %>
      </a>
      </li>
      </ul>
      </div>
      </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class = 'container-large'>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1602230167211-dfcbd679ed00?q=80&w=2912&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')">
    <div class="container">
    <h1><strong> Discover the best movies of all times </strong></h1>
    <p> Get your popcorn 🍿, and dive into your watchlists. Curated by friends, family and yourself. A beautiful collection. 🎬 </p>
    </div>
    <div class="list-items">
    <div>
    <% @lists.each do |list| %>
    <a class="btn btn-ghost" href="<%=list_path(list)%>">
    <%= list.name %>
    </a>
    <% end %>
    </div>
  </div>
  </div>
</div>

<%# <%= cl_image_tag("i1xrx778nld9g1yppenf",
      width: 400, height: 300, crop: :fill) %>

app/views/lists/new.html.erb
<div class ="container py-5">
  <div class= "row">
    <div class="col-12 col-md-6 offset-lg-3">
      <h1> Create a new movie list </h1>
      <h3><i> & share with your friends</i> 😉 </h3>
      <%= simple_form_for(@list) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        </div>
        <div class="form-actions">
        <%= f.button :submit, class: "btn btn-ghost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.photo.present?%>
<div class="list-banner"   style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, crop: :fill %>')">
  <h2>
  <%= @list.name %>
  </h2>
</div>
<% else %>
<div class="list-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://media.istockphoto.com/id/1467934174/photo/film-reel-cinema-or-photography-35mm-film-strip-tape-3d-illustration-isolated-on-the-white.webp?b=1&s=170667a&w=0&k=20&c=jfL-Qo7xDMFShvLTrmg3yEurE5p5q_6GNXp37k-LqgI=')">
  <h2>
  <%= @list.name%>
  </h2>
</div>\
<% end %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
      <ul class="nav-item"><%= link_to "Add a movie", new_list_bookmark_path(@list) %> </ul>
      <ul class="nav-item"><%= link_to "Delete list", list_path(@list),
      data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></ul>
    </div>
</div>

    <%# <a class="btn btn-ghost" href="<%=list_path(list)%>

<div class="row">
<div class="side">
  <h3> Add your review </h3>
  <% if @list.reviews.empty? %>
  <small><em class="text-muted"> Be the first to review </em></small>
  <% end %>
  <% @list.reviews.each do |review| %>
    <div>
      <% review.rating.times do %>
      <i class="fas fa-star star-yellow"></i>
      <% end %>
      <p class="mb-0"><%= review.content %></p>
    </div>
  <% end %>
  <%= simple_form_for([@list, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content, placeholder: "Add your review here...", label: false %>
    <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { data: { controller: "star-rating" } } %>
    </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-ghost" %>
  </div>
  <% end %>
</div>


<div class="main">
  <% @list.bookmarks.each do |bookmark| %>
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="Card image cap">
        <div class="card-body">
    <h5 class="card-title"><%= bookmark.movie.title %> - <%= bookmark.movie.rating %></h5>
    <p class="card-text"><%= bookmark.movie.overview %></p>
    </div>
    <ul class="list-group list-group-flush">
    <li class="list-group-item">"<%= bookmark.comment%>"</li>
    <ul> <%= link_to 'Delete', bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    </div>
    <% end %>
    </ul>
    </ul>
</div>
</div>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>